### ISSUE TITLE
user-api is not able to handle `thamos advise`

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#1007]
**Describe the bug**
```
{"remote": "10.131.2.1", "date": "[25/Aug/2020:19:39:07 +0000]", "status": "202", "response_length": 3262, "referer": "-", "user_agent": "Thamos/0.11.1 (Python 3.8.2; Linux 5.7.14-200.fc32.x86_64)", "request_method": "POST", "url_path": "/api/v1/advise/python", "protocol": "HTTP/1.1", "request_time": 0}
{"remote": "10.131.4.1", "date": "[25/Aug/2020:19:39:07 +0000]", "status": "200", "response_length": 67, "referer": "-", "user_agent": "kube-probe/1.16+", "request_method": "GET", "url_path": "/readiness", "protocol": "HTTP/1.1", "request_time": 0}
2020-08-25 19:39:10,021  28 ERROR    thoth.user_api.openapi_server:1892: Exception on /api/v1/advise/python/adviser-db22b1a7 [GET]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 93, in retrieve_blob
    return self._s3.Object(self.bucket, f"{self.prefix}{object_key}").get()["Body"].read()
  File "/opt/app-root/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 760, in _get_document
    result = adapter.retrieve_document(analysis_id)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 114, in retrieve_document
    return self.ceph.retrieve_document(document_id)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 107, in retrieve_document
    return json.loads(self.retrieve_blob(document_id).decode())
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 96, in retrieve_blob
    raise NotFoundError("Failed to retrieve object, object {!r} does not exist".format(object_key)) from exc
thoth.storages.exceptions.NotFoundError: Failed to retrieve object, object 'adviser-db22b1a7' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 335, in get_advise_python
    AdvisersResultsStore, analysis_id, name_prefix="adviser-", namespace=Configuration.THOTH_BACKEND_NAMESPACE
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 775, in _get_document
    raise ValueError(f"Unreachable - unknown workflow state: {status}")
ValueError: Unreachable - unknown workflow state: {'finished_at': '2020-08-25T19:39:09Z', 'reason': None, 'started_at': '2020-08-25T19:39:06Z', 'state': 'error'}
{"remote": "10.131.2.1", "date": "[25/Aug/2020:19:39:10 +0000]", "status": "500", "response_length": 177, "referer": "-", "user_agent": "python-requests/2.22.0", "request_method": "GET", "url_path": "/api/v1/advise/python/adviser-db22b1a7", "protocol": "HTTP/1.1", "request_time": 0}
2020-08-25 19:39:14,060  28 ERROR    thoth.user_api.openapi_server:1892: Exception on /api/v1/advise/python/adviser-db22b1a7 [GET]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 93, in retrieve_blob
    return self._s3.Object(self.bucket, f"{self.prefix}{object_key}").get()["Body"].read()
  File "/opt/app-root/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 760, in _get_document
    result = adapter.retrieve_document(analysis_id)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 114, in retrieve_document
    return self.ceph.retrieve_document(document_id)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 107, in retrieve_document
    return json.loads(self.retrieve_blob(document_id).decode())
  File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 96, in retrieve_blob
    raise NotFoundError("Failed to retrieve object, object {!r} does not exist".format(object_key)) from exc
thoth.storages.exceptions.NotFoundError: Failed to retrieve object, object 'adviser-db22b1a7' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 335, in get_advise_python
    AdvisersResultsStore, analysis_id, name_prefix="adviser-", namespace=Configuration.THOTH_BACKEND_NAMESPACE
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 775, in _get_document
    raise ValueError(f"Unreachable - unknown workflow state: {status}")
ValueError: Unreachable - unknown workflow state: {'finished_at': '2020-08-25T19:39:09Z', 'reason': None, 'started_at': '2020-08-25T19:39:06Z', 'state': 'error'}
```

**To Reproduce**
1. https://prow.thoth-station.dev/log?job=integration-tests-periodic-preprod&id=1298298938314461184

Thamos Client version: 0.10.6
Thoth API https://api.preprod.thoth-station.ninja/khemenu/api/v1: 0.6.10

/kind bug
/priority critical-urgent
/assign @fridex

**Comment by goern** [comment]
/label deployment_name/ocp-stage

ocp-test is on v0.6.9 and seems to work.
