### ISSUE TITLE
user-api is in a crash loop

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#109]
NameError: name 'SolverResultsStore' is not defined, #108  is deployed...

```
---> Serving application with gunicorn (thoth_user_api.entrypoint:app) ...
--
  | [2018-05-17 17:43:38 +0000] [1] [INFO] Starting gunicorn 19.8.1
  | [2018-05-17 17:43:38 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080  (1)
  | [2018-05-17 17:43:38 +0000] [1] [INFO] Using worker: sync
  | [2018-05-17 17:43:38 +0000] [27] [INFO] Booting worker with pid: 27
  | [2018-05-17 17:43:38 +0000] [29] [INFO] Booting worker with pid: 29
  | [2018-05-17 17:43:38 +0000] [30] [INFO] Booting worker with pid: 30
  | [2018-05-17 17:43:38 +0000] [31] [INFO] Booting worker with pid: 31
  | 172.50.72.1 - - [17/May/2018:17:43:46 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:43:56 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:44:06 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:44:16 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:44:26 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:44:36 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | /opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  | InsecureRequestWarning)
  | ERROR:flask.app:Exception on /liveness [GET]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/src/thoth_user_api/entrypoint.py", line 81, in api_liveness
  | adapter = SolverResultsStore()
  | NameError: name 'SolverResultsStore' is not defined
  | 172.50.72.1 - - [17/May/2018:17:44:36 +0000] "GET /liveness HTTP/1.1" 500 252 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:44:46 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:44:56 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:45:06 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:45:16 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:45:26 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | 172.50.72.1 - - [17/May/2018:17:45:36 +0000] "GET /readiness HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
  | /opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  | InsecureRequestWarning)
  | ERROR:flask.app:Exception on /liveness [GET]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/src/thoth_user_api/entrypoint.py", line 81, in api_liveness
  | adapter = SolverResultsStore()
  | NameError: name 'SolverResultsStore' is not defined
  | 172.50.72.1 - - [17/May/2018:17:45:36 +0000] "GET /liveness HTTP/1.1" 500 252 "-" "Go-http-client/1.1"
  | [2018-05-17 17:45:36 +0000] [1] [INFO] Handling signal: term
  | [2018-05-17 17:45:36 +0000] [30] [INFO] Worker exiting (pid: 30)
  | [2018-05-17 17:45:36 +0000] [27] [INFO] Worker exiting (pid: 27)
  | [2018-05-17 17:45:36 +0000] [29] [INFO] Worker exiting (pid: 29)
  | [2018-05-17 17:45:36 +0000] [31] [INFO] Worker exiting (pid: 31)
  | [2018-05-17 17:45:37 +0000] [1] [INFO] Shutting down: Master

```

**Comment by fridex** [comment]
This is not related to master, but rather #108
