### ISSUE TITLE
build-watcher fails to submit build analysis request

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1200]
**Describe the bug**
```
2021-01-19 16:17:00,577  29 INFO     thoth.build_watcher:341: Handling analysis of image 'image-registry.openshift-image-registry.svc:5000/thoth-test-core/workflow-helpers:latest'
2021-01-19 16:17:00,733  29 ERROR    thoth.build_watcher:360: Failed to submit image 'image-registry.openshift-image-registry.svc:5000/thoth-test-core/workflow-helpers:latest' for analysis to Thoth: (400)
Reason: BAD REQUEST
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn/20.0.4', 'date': 'Tue, 19 Jan 2021 16:17:00 GMT', 'content-type': 'application/problem+json', 'content-length': '167', 'access-control-allow-origin': '*', 'x-thoth-version': '0.8.0', 'x-user-api-service-version': '0.8.0+messaging.0.7.13.storages.0.26.0.common.0.20.4.python.0.10.2', 'set-cookie': 'a804a8855c73e50e7b794932cd3bb7f5=da61f573ca9438ea266044a960a594c3; path=/; HttpOnly; Secure'})
HTTP response body: {
  "detail": "Extra query parameter(s) output_registry_verify_tls, base_registry_verify_tls not in spec",
  "status": 400,
  "title": null,
  "type": "about:blank"
}

Traceback (most recent call last):
  File "app.py", line 344, in _submitter
    _do_analyze_build(
  File "app.py", line 213, in _do_analyze_build
    analysis_response = build_analysis(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 102, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 758, in build_analysis
    response = api_instance.post_build(**params)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/thoth/build_analysis_api.py", line 63, in post_build
    (data) = self.post_build_with_http_info(body, **kwargs)  # noqa: E501
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/thoth/build_analysis_api.py", line 187, in post_build_with_http_info
    return self.api_client.call_api(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 343, in call_api
    return self.__call_api(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 157, in __call_api
    response_data = self.request(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 420, in request
    return self.rest_client.POST(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/rest.py", line 338, in POST
    return self.request(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/rest.py", line 250, in request
    raise ApiException(http_resp=r)
thamos.swagger_client.rest.ApiException: (400)
Reason: BAD REQUEST
HTTP response headers: HTTPHeaderDict({'server': 'gunicorn/20.0.4', 'date': 'Tue, 19 Jan 2021 16:17:00 GMT', 'content-type': 'application/problem+json', 'content-length': '167', 'access-control-allow-origin': '*', 'x-thoth-version': '0.8.0', 'x-user-api-service-version': '0.8.0+messaging.0.7.13.storages.0.26.0.common.0.20.4.python.0.10.2', 'set-cookie': 'a804a8855c73e50e7b794932cd3bb7f5=da61f573ca9438ea266044a960a594c3; path=/; HttpOnly; Secure'})
HTTP response body: {
  "detail": "Extra query parameter(s) output_registry_verify_tls, base_registry_verify_tls not in spec",
  "status": 400,
  "title": null,
  "type": "about:blank"
}
```

**To Reproduce**
1. Deploy the most recent build-watcher
2. See the errors

**Expected behavior**

build-watcher should be able to submit build analysis requests

**Comment by fridex** [comment]
I forgot to point the bot to the test environment, this is specific for the user-api version running in prod deployment. An update will fix this.
