### ISSUE TITLE
user api does not accept analyser requests

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#124]
**Describe the bug**
```
--- Logging error ---
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 352, in emit
  | self.socket.sendto(syslog_msg, self.address)
  | TypeError: an integer is required (got type str)
  | Call stack:
  | File "/opt/app-root/bin/gunicorn", line 11, in <module>
  | sys.exit(run())
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
  | WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
  | super(Application, self).run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
  | Arbiter(self).run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 212, in run
  | self.manage_workers()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
  | self.spawn_workers()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
  | self.spawn_worker()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
  | self.run()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 124, in run
  | self.run_for_one(timeout)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
  | self.accept(listener)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 30, in accept
  | self.handle(listener, client, addr)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
  | self.handle_request(listener, req, client, addr)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
  | respiter = self.wsgi(environ, resp.start_response)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apps/abstract.py", line 257, in __call__
  | return self.app(environ, start_response)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
  | return self.wsgi_app(environ, start_response)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 293, in wrapper
  | return function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 219, in wrapper
  | return function(**kwargs)
  | 172.50.12.1 - - [14/Jun/2018:08:20:17 +0000] "POST /api/v1/analyze?image=fedora%3A27&analyzer=fridex%2Fthoth-package-extract HTTP/1.1" 202 335 "-" "python-requests/2.18.4"
  | File "/opt/app-root/src/thoth_user_api/api_v1.py", line 49, in analyze
  | 'pod_id': run_analyzer(**params),
  | File "/opt/app-root/src/thoth_user_api/utils.py", line 138, in run_analyzer
  | return _do_run_pod(template, Configuration.THOTH_MIDDLETIER_NAMESPACE)
  | File "/opt/app-root/src/thoth_user_api/utils.py", line 64, in _do_run_pod
  | _LOGGER.error(response.text)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1335, in error
  | self._log(ERROR, msg, args, **kwargs)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1442, in _log
  | self.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1452, in handle
  | self.callHandlers(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 1514, in callHandlers
  | hdlr.handle(record)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/logging/__init__.py", line 863, in handle
  | self.emit(record)
  | File "/opt/app-root/lib/python3.6/site-packages/rfc5424logging/handler.py", line 356, in emit
  | self.handleError(record)

```

**Comment by fridex** [comment]
This looks like logging error - the request seems to be processed correctly - there was returned 202:

```
  | 172.50.12.1 - - [14/Jun/2018:08:20:17 +0000] "POST /api/v1/analyze?image=fedora%3A27&analyzer=fridex%2Fthoth-package-extract HTTP/1.1" 202 335 "-" "python-requests/2.18.4"
```
