### ISSUE TITLE
ValidationError: 'finished_at' is a required property

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1275]
**Describe the bug**

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/connexion/decorators/validation.py", line 226, in validate_schema
    self.validator.validate(data)
  File "/opt/app-root/lib64/python3.8/site-packages/jsonschema/validators.py", line 353, in validate
    raise error
jsonschema.exceptions.ValidationError: 'finished_at' is a required property

Failed validating 'required' in schema['properties']['status']:
    {'description': 'Status information about the analysis run.',
     'properties': {'finished_at': {'description': 'Datetime in ISO format '
                                                   'informing about when '
                                                   'the analysis has '
                                                   'finished.\n',
                                    'nullable': True,
                                    'type': 'string'},
                    'reason': {'description': 'Reasoning on finished run.',
                               'nullable': True,
                               'type': 'string'},
                    'started_at': {'description': 'Datetime in ISO format '
                                                  'informing about when '
                                                  'the analysis has '
                                                  'started.\n',
                                   'nullable': True,
                                   'type': 'string'},
                    'state': {'example': 'running', 'type': 'string'}},
     'required': ['finished_at', 'reason', 'started_at', 'state'],
     'type': 'object'}

On instance['status']:
    {'terminated': {'containerID': 'cri-o://8a8fefaae9d6125f64de32441040d6c044e1adf2ee0219d6f58aa38fa2209ac6',
                    'exitCode': 1,
                    'finishedAt': '2021-02-24T09:16:55Z',
                    'reason': 'Error',
                    'startedAt': '2021-02-24T09:16:34Z'}}
```

**To Reproduce**
1. Go to test environment
2. Run integration tests
3. See the error

**Comment by fridex** [comment]
Should be fixed by https://github.com/thoth-station/common/pull/1113 and available in thoth-common==0.24.0 https://github.com/thoth-station/common/pull/1119. Container is running thoth-common==0.24.0 but source code does not carry https://github.com/thoth-station/common/pull/1113 fix.
