### ISSUE TITLE
THOTH_S3_ENDPOINT_URL not set

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#137]
**Describe the bug**
user-api deployment needs `THOTH_S3_ENDPOINT_URL` ENV... May it be THOTH_CEPH_S3_ENDPOINT_URL by accident?

```

---> Serving application with gunicorn (thoth_user_api.entrypoint:app) ...
--
  | [2018-07-01 13:11:45 +0000] [1] [INFO] Starting gunicorn 19.8.1
  | [2018-07-01 13:11:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080  (1)
  | [2018-07-01 13:11:45 +0000] [1] [INFO] Using worker: sync
  | [2018-07-01 13:11:45 +0000] [27] [INFO] Booting worker with pid: 27
  | [2018-07-01 13:11:45 +0000] [28] [INFO] Booting worker with pid: 28
  | [2018-07-01 13:11:45 +0000] [29] [INFO] Booting worker with pid: 29
  | [2018-07-01 13:11:45 +0000] [30] [INFO] Booting worker with pid: 30
  | 2018-07-01 13:11:48,738 [28] INFO     root: Setting up logging to rsyslog endpoint 10.0.18.51:30514
  | 2018-07-01 13:11:48,738 [27] INFO     root: Setting up logging to rsyslog endpoint 10.0.18.51:30514
  | 2018-07-01 13:11:48,844 [29] INFO     root: Setting up logging to rsyslog endpoint 10.0.18.51:30514
  | 2018-07-01 13:11:49,045 [30] INFO     root: Setting up logging to rsyslog endpoint 10.0.18.51:30514
  | 2018-07-01 13:11:53,888 [28] ERROR    flask.app: Exception on /readiness [GET]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/src/thoth_user_api/entrypoint.py", line 93, in api_readiness
  | return _healthiness()
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/common/logging.py", line 114, in wrapper_func
  | return fn(*args, **kwargs)
  | File "/opt/app-root/src/thoth_user_api/entrypoint.py", line 79, in _healthiness
  | adapter = SolverResultsStore()
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/result_base.py", line 59, in __init__
  | region=region
  | File "/opt/app-root/lib/python3.6/site-packages/thoth/storages/ceph.py", line 43, in __init__
  | self.host = host or os.environ['THOTH_S3_ENDPOINT_URL']
  | File "/opt/app-root/lib64/python3.6/os.py", line 669, in __getitem__
  | raise KeyError(key) from None
  | KeyError: 'THOTH_S3_ENDPOINT_URL'


```

**Comment by goern** [comment]
re-applyed the deployment template, seems to work

**Comment by fridex** [comment]
It should be ``THOTH_S3_ENDPOINT_URL`` - https://github.com/thoth-station/storages/blob/master/thoth/storages/ceph.py#L43
