### ISSUE TITLE
user-api is down.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/user-api#1416]
**Describe the bug**
```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 380, in stop
    and not self.cfg.reuse_port
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/config.py", line 213, in reuse_port
    return self.settings['reuse_port'].get()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/app-root/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 380, in stop
    and not self.cfg.reuse_port
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/config.py", line 213, in reuse_port
    return self.settings['reuse_port'].get()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/opt/app-root/lib64/python3.8/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by fridex** [comment]
No longer relevant.

/close
