### ISSUE TITLE
`ImportError` from `click` causes pre-commit to fail

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/user-api#1734]
**Describe the bug**
See https://github.com/thoth-station/user-api/pull/1733#issuecomment-1081693703 and https://github.com/thoth-station/user-api/pull/1730#issuecomment-1081718468

**To Reproduce**
Open a PR in this repository and see the error for the `black` check.

**Expected behavior**
pre-commit check passes.

**Additional context**
Error log in Prow for https://github.com/thoth-station/user-api/pull/1733:

```
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/opt/app-root/src/.cache/pre-commit/repohvodjssb/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/app-root/src/.cache/pre-commit/repohvodjssb/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1127, in patched_main
    patch_click()
  File "/opt/app-root/src/.cache/pre-commit/repohvodjssb/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1113, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/app-root/src/.cache/pre-commit/repohvodjssb/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

**Comment by mayaCostantini** [comment]
It looks like the issue is recent and was raised recently in the `click` repository: https://github.com/pallets/click/issues/2232
