### ISSUE TITLE
user-api should not validate x509 cert of kube master

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#202]
**Describe the bug**
```

2018-08-31 12:57:54,285 [288] ERROR    thoth.user_api.api_v1: HTTPSConnectionPool(host='openshift.default.svc.cluster.local', port=443): Max retries exceeded with url: /apis/template.openshift.io/v1/namespaces/thoth-test-core/processedtemplates (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
--
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  | chunked=chunked)
  | File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
  | self._validate_conn(conn)
  | File "/opt/app-root/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
  | conn.connect()
  | File "/opt/app-root/lib/python3.6/site-packages/urllib3/connection.py", line 356, in connect
  | ssl_context=context)
  | File "/opt/app-root/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
  | return context.wrap_socket(sock, server_hostname=server_hostname)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
  | _context=self, _session=session)
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 814, in __init__
  | self.do_handshake()
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
  | self._sslobj.do_handshake()
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
  | self._sslobj.do_handshake()
  | ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)


```

**To Reproduce**
request an image analysis

**Expected behavior**
just do it, and do ont verify the x.509 cert of openshift.default.svc.cluster.local.

**Additional context**

**Comment by fridex** [comment]
Fixed in https://github.com/thoth-station/common/pull/80
