### ISSUE TITLE
type object 'V1ObjectMeta' has no attribute 'swagger_types' in argo-workflows==2.1.4

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#826]
**Describe the bug**

When running trying to schedule a workload using Argo, user-api responds with an internal error.

**To Reproduce**
1. Set `THOTH_USE_ARGO=1` in deployment
2. Try to run `thamos advise` on any repo
3. See error logs in deployment

**Expected behavior**

Argo should schedule advise workflow

**Additional context**

```
aiocontextvars==0.2.2
aiohttp==3.6.2
alembic==1.4.2
amun==0.4.3
argo-workflows==2.1.4
async-timeout==3.0.1
attrdict==2.0.1
attrs==19.3.0
beautifulsoup4==4.6.3
blinker==1.4
boto3==1.12.29
botocore==1.15.29
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
click==7.1.1
clickclick==1.2.2
connexion==2.6.0
contextlib2==0.6.0.post1
contextvars==2.4
daiquiri==2.1.1
delegator.py==0.1.1
dictdiffer==0.8.1
distro==1.4.0
docutils==0.15.2
Flask==1.1.1
Flask-Cors==3.0.8
Flask-Script==2.0.6
future==0.18.2
google-auth==1.11.3
grpcio==1.27.2
grpcio-opentracing==1.1.4
grpcio-tools==1.27.2
gunicorn==20.0.4
idna==2.9
idna-ssl==1.1.0
immutables==0.11
importlib-metadata==1.5.1
inflection==0.3.1
itsdangerous==1.1.0
jaeger-client==4.3.0
Jinja2==2.11.1
jmespath==0.9.5
jsonformatter==0.1.4
jsonschema==3.2.0
kubernetes==11.0.0
lxml==4.5.0
Mako==1.1.2
MarkupSafe==1.1.1
methodtools==0.1.2
mock==4.0.2
multidict==4.7.5
oauthlib==3.1.0
openapi-spec-validator==0.2.8
openshift==0.11.0
opentracing==2.3.0
opentracing-instrumentation==3.2.1
packaging==20.3
pexpect==4.8.0
prometheus-client==0.7.1
prometheus-flask-exporter==0.13.0
protobuf==3.11.3
psycopg2-binary==2.8.4
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyelftools==0.26
pyparsing==2.4.6
pyrsistent==0.16.0
python-dateutil==2.8.1
python-editor==1.0.4
python-json-logger==0.1.11
python-string-utils==1.0.0
pytz==2019.3
PyYAML==5.3.1
requests==2.23.0
requests-oauthlib==1.3.0
rfc5424-logging-handler==1.4.3
rsa==4.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3transfer==0.3.3
semantic-version==2.8.4
sentry-sdk==0.14.3
six==1.14.0
SQLAlchemy==1.3.15
SQLAlchemy-Utils==0.36.3
swagger-ui-bundle==0.0.6
thoth-analyzer==0.1.8
thoth-common==0.12.1
thoth-python==0.9.1
thoth-storages==0.22.5
threadloop==1.0.2
thrift==0.13.0
toml==0.10.0
tornado==5.1.1
typing-extensions==3.7.4.1
tzlocal==2.0.0
urllib3==1.25.8
voluptuous==0.11.7
websocket-client==0.57.0
Werkzeug==1.0.0
wirerope==0.3.1
wrapt==1.12.1
yarl==1.4.2
zipp==3.1.0
```

Exception raised:

```
Exception on /api/v1/advise/python [POST]
Traceback (most recent call last):
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/app-root/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 184, in wrapper
    response = function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 121, in wrapper
    return function(**kwargs)
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 327, in post_advise_python
    response, status = _do_schedule(parameters, _OPENSHIFT.schedule_adviser, output=Configuration.THOTH_ADVISER_OUTPUT)
  File "/opt/app-root/src/thoth/user_api/api_v1.py", line 820, in _do_schedule
    return {"analysis_id": runner(**parameters, **runner_kwargs), "parameters": parameters, "cached": False}, 202
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1517, in schedule_adviser
    "workflow_parameters": workflow_parameters,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/openshift.py", line 1097, in _schedule_workflow
    return workflow(**parameters)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 333, in submit_adviser_workflow
    workflow_namespace=self.openshift.backend_namespace,
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 272, in submit_workflow_from_template
    workflow: Workflow = Workflow.from_dict(workflow_object, validate=True)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 127, in from_dict
    return cls.from_string(json.dumps(wf), validate=validate)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 134, in from_string
    return cls.__deserialize(body, validate=validate)
  File "/opt/app-root/lib/python3.6/site-packages/thoth/common/workflows.py", line 143, in __deserialize
    wf = client.ApiClient().deserialize(attr, models.V1alpha1Workflow)
  File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 241, in deserialize
    return self.__deserialize(data, response_type)
  File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 624, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/opt/app-root/lib/python3.6/site-packages/argo/workflows/client/api_client.py", line 613, in __deserialize_model
    if (not klass.swagger_types and
AttributeError: type object 'V1ObjectMeta' has no attribute 'swagger_types'
```

**Comment by fridex** [comment]
I've set `THOTH_USE_ARGO` to 1 in test and stage until this gets resolved.

**Comment by CermakM** [comment]
The problem is in `kubernetes==11.0.0` ... this is not compatible and it shouldn't even be installed given the restrictions.

**Comment by CermakM** [comment]
Does the issue persist after https://github.com/thoth-station/user-api/issues/826 has been merged?

**Comment by fridex** [comment]
> Does the issue persist after #826 has been merged?

I've pushed the fix to stage, it looks like the fix addressed the issue. Thanks! :+1:
