### ISSUE TITLE
seeing 504 with erase-graph endpoint

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#93]
```

172.50.68.1 - - [25/Apr/2018:13:18:40 +0000] "POST /api/v1/erase-graph?secret=secret101 HTTP/1.1" 500 252 "-" "python-requests/2.18.4"
--
  | [2018-04-25 13:18:41,774] ERROR in app: Exception on /api/v1/erase-graph [POST]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
  | response = self.full_dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
  | rv = self.handle_user_exception(e)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
  | reraise(exc_type, exc_value, tb)
  | File "/opt/app-root/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
  | rv = self.dispatch_request()
  | File "/opt/app-root/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
  | return self.view_functions[rule.endpoint](**req.view_args)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 293, in wrapper
  | return function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 42, in wrapper
  | response = function(request)
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 219, in wrapper
  | return function(**kwargs)
  | File "/opt/app-root/src/thoth_user_api/api_v1.py", line 272, in erase_graph
  | loop.run_until_complete(adapter.g.V().drop().next())
  | File "/opt/rh/rh-python36/root/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
  | return future.result()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/process/graph_traversal.py", line 56, in next
  | return await self.__anext__()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/process/graph_traversal.py", line 17, in __anext__
  | self.last_traverser = await self.traversers.__anext__()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/driver/resultset.py", line 66, in __anext__
  | msg = await self.one()
  | File "/opt/app-root/lib/python3.6/site-packages/aiogremlin/driver/resultset.py", line 16, in wrapper
  | "{0}: {1}".format(msg.status_code, msg.message))
  | aiogremlin.exception.GremlinServerError: 500: 500: Could not commit transaction due to exception during persistence

```

**Comment by fridex** [comment]
Please reopen if the issue still persists.
